apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace:
  name: tomcat
spec:
  rules:
  - host: tomcat.cloud.noverit.com
    http:
      paths:
      - path: /
        backend:
          serviceName: taas
          servicePort: 8000

