apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog
spec:
  rules:
  - host: blog.cloud.noverit.com
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress
          servicePort: 80
