apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog
spec:
  rules:
  - host: blog.cloud.clastix.io
    http:
      paths:
      - path: /
      # path: /*
        backend:
          serviceName: wordpress
          servicePort: 80
