---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    # comment nodePort when using type: ClusterIP
    nodePort: 31000
  selector:
    run: nginx
  #type: ClusterIP
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
  name: nginx
spec:
  minReadySeconds: 15
  replicas: 3
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:1.12
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
