---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share01
  labels:
    name: share01
spec:
  capacity:
    storage: 1Gi
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  nfs:
    path: "/mnt/share-01"
    server: fileserver
  persistentVolumeReclaimPolicy: Recycle
